#!/bin/sh
FILEDIR=$HOME/Documents/git/dotfiles
cp -rf ~/.config/bspwm $FILEDIR/.config/
cp -rf ~/.config/sxhkd $FILEDIR/.config/
cp -rf ~/.config/compton.conf $FILEDIR/.config/compton/
cp -rf ~/.config/polybar $FILEDIR/.config/
cp -rf ~/.config/termite $FILEDIR/.config/
cp -rf ~/.Xresources $FILEDIR
cp -rf ~/Pictures/Wallpapers/wallpaper.* $FILEDIR/wallpaper/
cp -f /usr/bin/dotfiles $FILEDIR/backup-script

echo "dotfiles updated"
