#! /bin/sh

sxhkd &

bspc monitor DisplayPort-0 -d web music irssi
bspc monitor HDMI-0 -d term code code

bspc config border_width          1
bspc config window_gap            20

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config super                 mod4
bspc config pointer_action1       move
bspc config pointer_action2       none
bspc config pointer_action3       resize_corner
bspc config click_to_focus        true
bspc config normal_border_color   "#181512"
bspc config focused_border_color  "#b042f4"
bspc config presel_border_color   "#AC4142"
bspc config presel_feedback_color "#aaaaaa"

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill ~/Pictures/Wallpapers/wallpaper.png
compton --config ~/.config/compton.conf -b &
xset +fp /usr/share/fonts/local
xset fp rehash &

polybar left &
polybar right &
