#! /bin/sh

wm.start_sxhkd &
wm.start_background &
wm.start_composite &
wm.start_polybar &
wm.start_pcloud &
wm.start_redshift &

bspc monitor -d I II III IV V VI

bspc config border_width                      1
bspc config window_gap                        20
bspc config top_padding                       20
bspc config bottom_padding                    0
bspc config left_padding                      0
bspc config right_padding                     0

bspc config split_ratio                       0.52
bspc config borderless_monocle                true
bspc config gapless_monocle                   true
bspc config paddingless_monocle               true
bspc config focus_follows_pointer             false

bspc config super                 mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner
bspc config click_to_focus        true
bspc config normal_border_color   "#4e4f4c"
bspc config focused_border_color  "#a8b7b4"
bspc config presel_border_color   "#AC4142"
bspc config presel_feedback_color "#aaaaaa"

bspc rule -a firefox desktop='^1'
bspc rule -a kitty state=pseudo_tiled
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# bspc config external_rules_command "$(which bspwm-rules)"
