#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width                      0
bspc config window_gap                        20
bspc config top_padding                       15
bspc config bottom_padding                    15
bspc config left_padding                      0
bspc config right_padding                     0

bspc config split_ratio                       0.52
bspc config borderless_monocle                true
bspc config gapless_monocle                   true
bspc config focus_follows_pointer             true

bspc config super                 mod4
#bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner
bspc config click_to_focus        true
bspc config normal_border_color   "#171206"
bspc config focused_border_color  "#e0c88a"
bspc config presel_border_color   "#AC4142"
bspc config presel_feedback_color "#aaaaaa"

bspc config external_rules_command            "$HOME/.config/bspwm/bspwm-rules"
