#! /bin/sh

# Startup scripts
wm.start_sxhkd &
wm.start_background &
# wm.start_composite &
wm.start_polybar &
wm.start_pcloud &
wm.start_redshift &

# Give each monitor 6 workspaces.
for m in $(bspc query --monitors --names); do
    bspc monitor $m -d 1 2 3 4 5 6
done

# Border gap/padding
bspc config border_width                      2
bspc config window_gap                        20
bspc config top_padding                       20 # For polybar
bspc config bottom_padding                    0
bspc config left_padding                      0
bspc config right_padding                     0

# Border colours
bspc config normal_border_color   "#4e4f4c"
bspc config focused_border_color  "#a8b7b4"
bspc config presel_border_color   "#AC4142"
bspc config presel_feedback_color "#aaaaaa"

# Tiling behaviour
bspc config split_ratio                       0.52
bspc config borderless_monocle                true
bspc config gapless_monocle                   true
bspc config paddingless_monocle               true
bspc config focus_follows_pointer             true

# Key/Input behavious
bspc config super                 mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner
bspc config click_to_focus        false

# Window rules
bspc rule -a kitty state=pseudo_tiled
bspc rule -a tdrop state=floating
bspc rule -a polybar state=locked follow=on sticky=on
