#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -xoffset -10 -yoffset 40 -width 10 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< "> Lock|> Logout|> Reboot|> Shutdown")"
  case "$MENU" in
    *Logout) qdbus org.kde.ksmserver /KSMServer logout 0 3 3 ;;
    *Reboot) systemctl reboot ;;
    *Shutdown) systemctl -i poweroff
  esac
