#! /bin/sh

# Startup scripts
start_sxhkd &
start_background &
start_composite &
#sleep 0.5
start_polybar &

# Give each monitor 6 workspaces.
for m in $(bspc query --monitors --names); do
  bspc monitor $m -d 1 2 3 4 5 6
done

# Shorthand function
_() { bspc config "$@"; }

# Border gap/padding
_ border_width              2
_ window_gap                20

# Top and bottom padding to account for polybar
_ top_padding               0
_ bottom_padding            0
_ left_padding              0
_ right_padding             0

# Border colours
_ normal_border_color       "#4e4f4c"
_ focused_border_color      "#a8b7b4"
_ presel_border_color       "#AC4142"
_ presel_feedback_color     "#aaaaaa"

# Tiling behaviour
_ split_ratio               0.52
_ borderless_monocle        true
_ gapless_monocle           true
_ paddingless_monocle       true
_ single_monocle            true

# Key/Input behavious
_ super                     mod4
_ pointer_action1           move
_ pointer_action2           resize_side
_ pointer_action3           resize_corner
_ click_to_focus            true
_ focus_follows_pointer     false
_ pointer_follows_pointer   false

# Window rules
bspc rule -a Alacritty      state=pseudo_tiled
bspc rule -a feh            state=pseudo_tiled
bspc rule -a Wpg			state=floating

bspc subscribe node_state | while read -r _ _ _ node state status; do
    if [[ "$state" == "monocle" ]]; then
        case "$status" in
            off) xprop -id "$node" -remove _COMPTON_SHADOW;;
            on) xprop -id "$node" -f _COMPTON_SHADOW 32c -set _COMPTON_SHADOW 1;;
        esac
    fi
done
