#!/usr/bin/python

import urllib.request, json

city = "Brisbane"
api_key = "a26a40b0e94be445fa580bc4b4ab1958"

weather = eval(str(urllib.request.urlopen("http://api.openweathermap.org/data/2.5/weather?q={}&APPID={}".format(city, api_key)).read())[2:-1])

info = weather["weather"][0]["description"].capitalize()
temp = int(float(weather["main"]["temp"]) - 272.15)

print("%s, %i °C" % (info, temp))
